### ISSUE TITLE
Remove archived repositories

### ISSUE THREAD

**Issue by micalevisk** [nestjs/awesome-nestjs#137]
Hey! This is a list of all archived repositories that I found in your [`README.md`](https://github.com/juliandavidmr/awesome-nestjs/blob/73ec769333090bba5dabb8c8992a0ec6d2c9d495/README.md):

```
adrien2p/nest-js-api-ai
BruceHem/simple-todos
mentos1386/lynx
evebook/api
nestjsx/automapper
adrien2p/nest-js-graphql
nest-cloud/nest-memcached
```

You could remove them or use the `~~` to scratch them, idk. Like 

- ~[foo](foo.com)~

:smile: 

---

btw I've made this simple script grab github repos and list the archived ones:

<details>
<summary><code>list_archived_repos.sh</code></summary>

```bash
#!/bin/bash

repos=($(grep --color=never -Po '(?<=github.com/)[^/]+/[^)/]+' "README.md"))
archived_repos=()

GH_PAT="your personal access token here"

for repo in "${repos[@]}"; do
  is_archived=$(curl -s -L -H "Authorization: token ${GH_PAT}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${repo}" | jq '.archived')
  if [ "$is_archived" == "true" ]; then
    archived_repos+=("$repo")
  fi
done

printf '%s\n' "${archived_repos[@]}"
```

</details>

_(maybe you can create a scheduler task with github action to do some health check, like broken link checker, archived repo checker)_

**Comment by juliandavidmr** [comment]
Hi @micalevisk, great contribution, I will be checking it later to implement. Thanks.

**Comment by jmcdo29** [comment]
Thanks for the script @micalevisk. Just removed the archived repositories from the readme, and we'll look into the automation for this when we've got some time (I do love the idea of it)

**Comment by micalevisk** [comment]
Just found these others:

https://github.com/mentos1386/nest-morgan
https://github.com/szokodiakos/typegoose

https://github.com/nestjs/awesome-nestjs/blob/c62f49a1a692881a1f7b2e1d4a641a11920adc1d/README.md?plain=1#L170
https://github.com/nestjs/awesome-nestjs/blob/c62f49a1a692881a1f7b2e1d4a641a11920adc1d/README.md?plain=1#L204
