### ISSUE TITLE
Add 'testing' category under 'Components & Libraries'

### ISSUE THREAD

**Issue by micalevisk** [nestjs/awesome-nestjs#158]
I think there are couple good resources & packages out there regarding tests for Nestjs projects, like:

- https://github.com/jmcdo29/testing-nestjs _A repository to show off to the community methods of testing NestJS including Unit Tests, Integration Tests, E2E Tests, pipes, filters, interceptors, GraphQL, Mongo, TypeORM, and more!_
- https://www.npmjs.com/package/@golevelup/ts-jest _Utilities for making testing NestJS applications easier. Currently supports Jest._

and since Nestjs's docs doesn't mention them (AFIK), it would be cool to have them listed here :D

Maybe the first one could live under `Resources > Examples`

**Comment by jmcdo29** [comment]
Closed with #168
