### ISSUE TITLE
Get ride of two archived repositories

### ISSUE THREAD

**Issue by micalevisk** [nestjs/awesome-nestjs#177]
https://github.com/nestjs/awesome-nestjs/blob/660e892261f74ba20abeb438fcade3fa5efb9abb/README.md#L177

https://github.com/nestjs/awesome-nestjs/blob/660e892261f74ba20abeb438fcade3fa5efb9abb/README.md#L219

I've used the following bash script to find them:

```bash
wget https://raw.githubusercontent.com/nestjs/awesome-nestjs/master/README.md
./list_archived_repos.sh
```

<details>
<summary><code>list_archived_repos.sh</code></summary>

```bash
#!/bin/bash

FILE="${1:-README.md}"

repos=($(grep --color=never -Po '(?<=github.com/)[^/]+/[^)/]+' $FILE))
archived_repos=()

GH_PAT="YOUR PERSONAL ACCESS TOKEN"

for repo in "${repos[@]}"; do
  follow_rules=$(
    curl -s -L -H "Authorization: token ${GH_PAT}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${repo}" | 
    jq '.archived == false'
  )

  echo -n "$repo"
  if [ "$follow_rules" == "false" ]; then
    archived_repos+=("$repo")
    echo "❌"
  else
    echo "✅"
  fi

  # sleep 2
done

echo "--------------------"
printf '%s\n' "${archived_repos[@]}"

```

</details>

**Comment by jmcdo29** [comment]
[Nest Typegoose](https://github.com/kpfromer/nestjs-typegoose) doesn't look to be archived, but Nest Morgan does. Feel free to open a PR to remove it

**Comment by micalevisk** [comment]
I've paste the wrong link

My script just found the https://github.com/szokodiakos/typegoose archived one actually
