### ISSUE TITLE
nestjs-query Easy CRUD for GraphQL.

### ISSUE THREAD

**Issue by Diluka** [nestjs/awesome-nestjs#192]
https://github.com/doug-martin/nestjs-query

**Comment by jmcdo29** [comment]
Want to make a PR to add the link?

**Comment by micalevisk** [comment]
looks like this can be closed.

https://github.com/nestjs/awesome-nestjs/blob/158e83e9aab1f0c2008b74680d6a071373f6ea6b/README.md#L184
