### ISSUE TITLE
Eventstore for Nestjs

### ISSUE THREAD

**Issue by kodeine** [nestjs/awesome-nestjs#209]
Please add [Eventstore for Nestjs](https://github.com/PrestaShopCorp/nestjs-geteventstore)

**Comment by jmcdo29** [comment]
Would you like to make a PR to add it to the README?

**Comment by kodeine** [comment]
@jmcdo29  i tried but it gives me 

```
git push --set-upstream origin feat/eventstore
remote: Permission to nestjs/awesome-nestjs.git denied to kodeine.
fatal: unable to access 'https://github.com/nestjs/awesome-nestjs/': The requested URL returned error: 403
```

**Comment by jmcdo29** [comment]
So fork it, push to your fork, and make a PR across forks, as you would for almost any other open source project
