### ISSUE TITLE
Propose to add a New NestJs template + Toolkit

### ISSUE THREAD

**Issue by rudemex** [nestjs/awesome-nestjs#222]
Hi, how are you? I would like to propose to add to the list a project I have been working on for more than 1 year.
It is a Nestjs starter project, in which you clone the repository and you have a functional application ready to be deployed in different environments through a centralized configuration.
Along with this starter, there is a library of modules with plug and play functionality, which is fed with this centralized configuration, so the developer will not have to spend time building configurations.

If you have any questions, do not hesitate to contact me.

Best regards.

NestJS Starter: https://github.com/rudemex/nestjs-starter
NestJs Toolkit: https://github.com/tresdoce/tresdoce-nestjs-toolkit

**Comment by jmcdo29** [comment]
Feel free to make a PR to add this
