### ISSUE TITLE
QQ group had been deleted?

### ISSUE THREAD

**Issue by kaikaibenkai** [nestjs/awesome-nestjs#267]
![Screenshot_20231030_231157.jpg](https://github.com/nestjs/awesome-nestjs/assets/99722991/ce69c57a-4d8f-4d71-9cc1-2b8271d8420d)

(you can download QQ [here](https://im.qq.com/) offically)

**Comment by micalevisk** [comment]
If it isn't accessible anymore, then yes

Feel free to open a PR to remove it from here

**Comment by kaikaibenkai** [comment]
@micalevisk done

I'm sure that the group no longer exists.
![image](https://github.com/nestjs/awesome-nestjs/assets/99722991/6d6102af-aad4-4362-9b72-4178c88e5ee8)
