### ISSUE TITLE
I think we should eliminate some projects that are no longer maintained, such as notadd, where the issue has not been recovered

### ISSUE THREAD

**Issue by LeoKun1231** [nestjs/awesome-nestjs#274]

**Comment by jmcdo29** [comment]
Absolutely agree. Would you like to determine which ones should be removed and make a PR for it?

**Comment by ezalivadnyi** [comment]
[@fusionworks/ra-data-nest-crud](https://github.com/FusionWorks/react-admin-nestjsx-crud-dataprovider) is outdated.

[React-admin wesite ](https://marmelab.com/react-admin/DataProviderList.html)suggests to use https://github.com/rayman1104/ra-data-nestjsx-crud instead
