### ISSUE TITLE
Nestjs + Passport + oAuth2 example

### ISSUE THREAD

**Issue by vanishdark** [nestjs/awesome-nestjs#81]
Hey Julian, I made an example of oAuth use with passport and nestjs.

I get help from nestjs guys on discord to finish this example. I'm using myself this example on my company authentication.

This example only needs to set up the environment file and people add some login in service file and are ready to go.

To give you some context people access to your api (example), the api redirect you to the oAuth provider return you to the page you set up to redirect.

example:
client -> server -> oAuthProvider -> server -> client

this example doesn't have an oAuth2 implementation but a redirect to a provider that give the people some control what can and cannot user have access from your provider.

If you think is useful for other people you can share on your links. 

https://gitlab.com/vanishdark/nestjs-oauth2-example

**Comment by juliandavidmr** [comment]
Hi @vanishdark, can you share a project that uses this example?

**Comment by vanishdark** [comment]
Hey @juliandavidmr i can not because is an private project from my company...

But I can do I project with angular simulating that... Just need to get a oAuth provider

**Comment by juliandavidmr** [comment]
Hi @vanishdark 
Can you create a pull request?

**Comment by vanishdark** [comment]
Sorry, @juliandavidmr I was busy with work could come here early. What pull request do you need?

**Comment by juliandavidmr** [comment]
@vanishdark ,
A pull request with your gitlab link.

**Comment by micalevisk** [comment]
I guess we can close this by now

![image](https://github.com/nestjs/awesome-nestjs/assets/13461315/c0427668-5e7b-4781-83c9-517b06745bcb)

**Comment by vanishdark** [comment]
> I guess we can close this by now
> 
> ![image](https://user-images.githubusercontent.com/13461315/274422534-c0427668-5e7b-4781-83c9-517b06745bcb.png)

Hey mica you can close the project is really outdated right now.
